@startuml


class Game {
  +cards1:array
  +cards2:array
  +__construct():void
  +start():array
  +getRule():Rule

}

class Player {

}

class Dealer {

}

class Card {
  +CARD_RANK:array
  -suitNumber:string
  +__construct():void
  +getRank():int
}
class HandEvaluator {
  -rule:Rule
  +__construct():void
  +getHand():array
  +getWinner():int
}

interface Rule {
  +HIGH_CARD:string
  +STRAIGHT:string
  +getHand():array
  +getWinner():int
}


class ThreeCardRule implements Rule {
  +HIGH_CARD:string
  +STRAIGHT:string
  +PAIR:string
  +THREE_CARD:string
  +HAND_RANK:array
  +getHand():array
  +getWinner():int
  +isPair():bool
  +isStraight():bool
  +isA23Straight():bool
  +isMinMax():bool
  +isThreeCard():bool
}

Game "1" o-- "2..3" Card:1ゲームにつき\n2 or 3枚配られる?
Game "1" o-- "2" HandEvaluator:1ゲームにつき\n2プレイヤーの判定？
HandEvaluator "1" o-- ThreeCardRule


@enduml
